import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  bn: {
    'nav.home': 'হোম',
    'nav.products': 'পণ্যসমূহ',
    'nav.about': 'আমাদের সম্পর্কে',
    'nav.resources': 'রিসোর্স',
    'nav.contact': 'যোগাযোগ',
    'nav.quote': 'কোটেশন পান',
    'nav.callNow': 'কল করুন',
    'hero.title': 'পুষ্টিকর বৃদ্ধি, ',
    'hero.titleAccent': 'সর্বোচ্চ মুনাফা',
    'hero.desc': 'প্রিমিয়াম পোল্ট্রি এবং ক্যাটল ফিড সমাধান।',
    'hero.explore': 'আমাদের পণ্য',
    'hero.learnMore': 'আরও জানুন',
    'features.title': 'আমাদের মূল সুবিধাসমূহ',
    'features.subtitle': 'উদ্ভাবনী ফর্মুলা, প্রমাণিত ফলাফল',
    'features.protein': 'উচ্চ শক্তি ও পুষ্টি',
    'features.proteinDesc': 'সর্বোত্তম বৃদ্ধির জন্য উচ্চ মানের পুষ্টি।',
    'features.amino': 'কঠোর মান নিয়ন্ত্রণ',
    'features.aminoDesc': 'প্রতিটি ধাপে গুণমান নিশ্চিত করা।',
    'features.stability': 'দ্রুত বৃদ্ধি এবং অধিক দুধ',
    'features.stabilityDesc': 'গবাদি পশুর দ্রুত বৃদ্ধি এবং দুধ উৎপাদন বৃদ্ধি।',
    'features.profit': 'খামারিদের জন্য উচ্চ মুনাফা',
    'features.profitDesc': 'কম খরচে অধিক লাভ নিশ্চিত করা।',
    'whyChoose.title': 'কেন আমাদের বেছে নেবেন',
    'whyChoose.research': 'গবেষণা-ভিত্তিক',
    'whyChoose.ingredients': 'প্রিমিয়াম উপকরণ',
    'whyChoose.manufacturing': 'উন্নত উৎপাদন',
    'contact.cta': 'আজই আমাদের সাথে যোগাযোগ করুন!',
    'contact.callUs': 'আমাদের কল করুন: +৮৮০১৮১৭৮৭৫১৩৯',
    'contact.sendMessage': 'বার্তা পাঠান',
    'products.title': 'আমাদের পণ্য তালিকা',
    'products.desc': 'প্রথম দিন থেকে বাজারজাত করা পর্যন্ত, আপনার ব্রয়লারের জন্য আমাদের কাছে নিখুঁত পুষ্টির প্রোফাইল রয়েছে।',
    'products.viewDetails': 'বিস্তারিত দেখুন',
    'products.addToCart': 'অর্ডার করতে কল করুন',
    'cta.title': 'আপনার খামারের লাভ বাড়াতে প্রস্তুত?',
    'cta.desc': 'আপনার পোল্ট্রি পুষ্টির প্রয়োজনে বিনামূল্যে পরামর্শের জন্য আজই আমাদের বিশেষজ্ঞদের সাথে যোগাযোগ করুন। আমরা আপনার সাফল্যে সাহায্য করতে এখানে আছি।',
    'cta.whatsapp': 'হোয়াটসঅ্যাপে চ্যাট করুন',
    'cta.call': 'এখনই কল করুন',
    'footer.about': 'প্রিমিয়াম পোল্ট্রি ফিড সমাধানে অগ্রণী। আমাদের লক্ষ্য হলো সর্বোচ্চ লাভজনকতার জন্য উচ্চ-মানের, বৈজ্ঞানিকভাবে তৈরি পুষ্টির মাধ্যমে খামারিদের ক্ষমতায়ন করা।',
    'footer.quickLinks': 'দ্রুত লিঙ্ক',
    'footer.products': 'পণ্যসমূহ',
    'footer.contact': 'যোগাযোগ করুন',
    'footer.address': 'পলওয়েল কার্নেশন শপিং সেন্টার। প্লট নং ৯/বি, লেভেল ৭, সেক্টর ০৮, উত্তরা, ঢাকা ১২৩০',
    'details.back': 'পণ্য তালিকায় ফিরে যান',
    'details.highlights': 'মূল বৈশিষ্ট্যসমূহ',
    'details.overview': 'পণ্য প্রোফাইল ওভারভিউ',
    'details.characteristics': 'ভৌত বৈশিষ্ট্য',
    'details.performance': 'বৃদ্ধি কর্মক্ষমতা',
    'details.nutritional': 'পুষ্টির হাইলাইটস',
    'details.seasonal': 'ঋতুভিত্তিক পারফরম্যান্স স্থিতিশীলতা',
    'details.summer': '☀️ গ্রীষ্মকাল',
    'details.monsoon': '🌧️ বর্ষাকাল',
    'details.winter': '❄️ শীতকাল',
    'details.advantages': 'প্রতিযোগিতামূলক সুবিধা',
    'details.interested': 'এই পণ্যটিতে আগ্রহী?',
    'details.commitment': 'MI UNIFYLD AGRO LTD গুণমানের প্রতিশ্রুতি',
    'details.duration': 'সময়কাল',
    'details.packaging': 'প্যাকেজিং',
    'about.title': 'আমাদের সম্পর্কে',
    'about.mission': 'আমাদের লক্ষ্য',
    'contact.title': 'যোগাযোগ করুন',
    'contact.form.name': 'আপনার নাম',
    'contact.form.email': 'আপনার ইমেল',
    'contact.form.message': 'আপনার বার্তা',
    'contact.form.send': 'বার্তা পাঠান',
    '404.title': 'পৃষ্ঠাটি পাওয়া যায়নি',
    '404.desc': 'দুঃখিত, আপনি যে পৃষ্ঠাটি খুঁজছেন তা খুঁজে পাওয়া যায়নি।',
    '404.back': 'হোমে ফিরে যান',
    'products.poultry': 'পোল্ট্রি ফিড রেঞ্জ',
    'products.cattle': 'ক্যাটল ফিড রেঞ্জ',
    'products.viewPoultry': 'পোল্ট্রি রেঞ্জ দেখুন',
    'products.viewCattle': 'ক্যাটল রেঞ্জ দেখুন',
    'products.poultryTitle': 'পোল্ট্রি ফিড',
    'products.cattleTitle': 'ক্যাটল ফিড',
    'products.viewAll': 'সব পণ্য দেখুন',
    'products.price': 'মূল্য',
    'products.callUs': 'কল করুন',
    'nav.emailUs': 'ইমেল করুন',
    'about.heroDesc': 'MI UNIFYLD AGRO LTD গবাদি পশুর পুষ্টি শিল্পে একটি অগ্রগামী প্রতিষ্ঠান, যা আধুনিক খামারের জন্য সর্বোচ্চ মানের সমাধান প্রদানে নিবেদিত।',
    'about.qualityFirst': 'গুণমান প্রথম',
    'about.qualityDesc': 'প্রতিটি ব্যাচ শ্রেষ্ঠত্বের জন্য পরীক্ষিত',
    'about.precisionNutrition': 'প্রিসিশন নিউট্রিশনের মাধ্যমে খামারিদের ক্ষমতায়ন',
    'about.missionDesc': 'আমাদের লক্ষ্য হলো খামারিদের উচ্চ-মানের, বৈজ্ঞানিকভাবে তৈরি পুষ্টির মাধ্যমে ক্ষমতায়ন করা যা সর্বোচ্চ বৃদ্ধি, স্বাস্থ্য এবং মুনাফা নিশ্চিত করে। আমরা টেকসই কৃষিতে বিশ্বাস করি।',
    'about.qa': 'গুণমান নিশ্চিতকরণ',
    'about.support': 'খামারি সহায়তা',
    'contact.desc': 'আপনার কি কোনো প্রশ্ন আছে বা অর্ডার করতে চান? আমরা আপনার খামার বৃদ্ধিতে সাহায্য করতে এখানে আছি।',
    'contact.info': 'যোগাযোগের তথ্য',
    'contact.office': 'আমাদের অফিস',
    'contact.phone': 'ফোন নম্বর',
    'contact.email': 'ইমেল ঠিকানা',
    'contact.social': 'সোশ্যাল কানেক্ট',
    'contact.whatsapp': 'হোয়াটসঅ্যাপ',
    'contact.messenger': 'মেসেঞ্জার',
    'contact.sendMsg': 'আমাদের একটি বার্তা পাঠান',
    'contact.success': 'আপনার বার্তা সফলভাবে পাঠানো হয়েছে!',
    'contact.error': 'বার্তা পাঠাতে ব্যর্থ হয়েছে। আবার চেষ্টা করুন।',
    'details.notFound': 'পণ্যটি পাওয়া যায়নি',
    'details.sendEmail': 'ইমেল পাঠান',
    'seo.home.title': 'MI UNIFYLD AGRO LTD | প্রিমিয়াম পোল্ট্রি ও ক্যাটল ফিড',
    'seo.home.desc': 'বাংলাদেশে প্রিমিয়াম পোল্ট্রি এবং ক্যাটল ফিড সমাধান। MI UNIFYLD AGRO LTD খামারিদের জন্য উচ্চ-মানের পুষ্টি সরবরাহ করে।',
    'seo.about.title': 'আমাদের সম্পর্কে | MI UNIFYLD AGRO LTD',
    'seo.about.desc': 'MI UNIFYLD AGRO LTD সম্পর্কে জানুন - বাংলাদেশে গবাদি পশুর পুষ্টির অগ্রগামী।',
    'seo.contact.title': 'যোগাযোগ করুন | MI UNIFYLD AGRO LTD',
    'seo.contact.desc': 'অর্ডার বা অনুসন্ধানের জন্য MI UNIFYLD AGRO LTD-এর সাথে যোগাযোগ করুন।',
  },
  en: {
    'nav.home': 'Home',
    'nav.products': 'Products',
    'nav.about': 'About Us',
    'nav.resources': 'Resources',
    'nav.contact': 'Contact',
    'nav.quote': 'Get a Quote',
    'nav.callNow': 'Call Now',
    'hero.title': 'Nourishing Growth, ',
    'hero.titleAccent': 'Maximizing Profit',
    'hero.desc': 'Premium Poultry & Cattle Feed Solutions.',
    'hero.explore': 'Our Products',
    'hero.learnMore': 'Learn More',
    'features.title': 'OUR KEY BENEFITS',
    'features.subtitle': 'Innovative Formulas, Proven Results',
    'features.protein': 'High Energy & Nutrition',
    'features.proteinDesc': 'High quality nutrition for optimal growth.',
    'features.amino': 'Strict Quality Control',
    'features.aminoDesc': 'Ensuring quality at every step.',
    'features.stability': 'Faster Growth & More Milk',
    'features.stabilityDesc': 'Rapid growth and increased milk production.',
    'features.profit': 'Higher Profit for Farmers',
    'features.profitDesc': 'Ensuring more profit with less cost.',
    'whyChoose.title': 'WHY CHOOSE US',
    'whyChoose.research': 'Research-Based',
    'whyChoose.ingredients': 'Premium Ingredients',
    'whyChoose.manufacturing': 'Advanced Manufacturing',
    'contact.cta': 'CONTACT US TODAY!',
    'contact.callUs': 'Call Us: +8801817875139',
    'contact.sendMessage': 'Send Message',
    'products.title': 'Our Product Lineup',
    'products.desc': 'From day one to market-ready, we have the perfect nutritional profile for your broilers.',
    'products.viewDetails': 'View Details',
    'products.addToCart': 'Call to Order',
    'cta.title': 'Ready to Boost Your Farm\'s Profit?',
    'cta.desc': 'Contact our experts today for a free consultation on your poultry nutrition needs. We are here to help you succeed.',
    'cta.whatsapp': 'Chat on WhatsApp',
    'cta.call': 'Call Us Now',
    'footer.about': 'Leading the way in premium poultry feed solutions. Our mission is to empower farmers with high-quality, scientifically formulated nutrition for maximum profitability.',
    'footer.quickLinks': 'Quick Links',
    'footer.products': 'Products',
    'footer.contact': 'Contact Us',
    'footer.address': 'Polwel Carnation Shopping Center . Plot No 9/B , Level 7, Sector 08, Uttara, Dhaka 1230',
    'details.back': 'Back to Products',
    'details.highlights': 'Key Highlights',
    'details.overview': 'Product Profile Overview',
    'details.characteristics': 'Physical Characteristics',
    'details.performance': 'Growth Performance',
    'details.nutritional': 'Nutritional Highlights',
    'details.seasonal': 'Seasonal Performance Stability',
    'details.summer': '☀️ Summer',
    'details.monsoon': '🌧️ Monsoon',
    'details.winter': '❄️ Winter',
    'details.advantages': 'Competitive Advantages',
    'details.interested': 'Interested in this product?',
    'details.commitment': 'MI UNIFYLD AGRO LTD Quality Commitment',
    'details.duration': 'Duration',
    'details.packaging': 'Packaging',
    'about.title': 'About Us',
    'about.mission': 'Our Mission',
    'contact.title': 'Contact Us',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Your Email',
    'contact.form.message': 'Your Message',
    'contact.form.send': 'Send Message',
    '404.title': 'Page Not Found',
    '404.desc': 'Sorry, the page you are looking for could not be found.',
    '404.back': 'Back to Home',
    'products.poultry': 'Poultry Feed Range',
    'products.cattle': 'Cattle Feed Range',
    'products.viewPoultry': 'View Poultry Range',
    'products.viewCattle': 'View Cattle Range',
    'products.poultryTitle': 'Poultry Feed',
    'products.cattleTitle': 'Cattle Feed',
    'products.viewAll': 'View All Products',
    'products.price': 'Price',
    'products.callUs': 'Call Us',
    'nav.emailUs': 'Email Us',
    'about.heroDesc': 'MI UNIFYLD AGRO LTD is a pioneer in the livestock nutrition industry, dedicated to providing the highest quality solutions for modern farming.',
    'about.qualityFirst': 'Quality First',
    'about.qualityDesc': 'Every batch is tested for excellence',
    'about.precisionNutrition': 'Empowering Farmers with Precision Nutrition',
    'about.missionDesc': 'Our mission is to empower farmers with high-quality, scientifically formulated nutrition that ensures maximum growth, health, and profitability. We believe in sustainable agriculture.',
    'about.qa': 'Quality Assurance',
    'about.support': 'Farmer Support',
    'contact.desc': 'Have questions or need to place an order? We\'re here to help you grow your farm.',
    'contact.info': 'Contact Information',
    'contact.office': 'Our Office',
    'contact.phone': 'Phone Number',
    'contact.email': 'Email Address',
    'contact.social': 'Social Connect',
    'contact.whatsapp': 'WhatsApp',
    'contact.messenger': 'Messenger',
    'contact.sendMsg': 'Send us a Message',
    'contact.success': 'Your message has been sent successfully!',
    'contact.error': 'Failed to send message. Please try again.',
    'details.notFound': 'Product not found',
    'details.sendEmail': 'Send Email',
    'seo.home.title': 'MI UNIFYLD AGRO LTD | Premium Poultry & Cattle Feed',
    'seo.home.desc': 'Premium poultry and cattle feed solutions in Bangladesh. MI UNIFYLD AGRO LTD provides high-quality nutrition for farmers.',
    'seo.about.title': 'About Us | MI UNIFYLD AGRO LTD',
    'seo.about.desc': 'Learn about MI UNIFYLD AGRO LTD - Pioneers in livestock nutrition in Bangladesh.',
    'seo.contact.title': 'Contact Us | MI UNIFYLD AGRO LTD',
    'seo.contact.desc': 'Contact MI UNIFYLD AGRO LTD for orders or inquiries.',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('bn');

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
